//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.34014
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

public class Cache<T> where T : UnityEngine.Object
{
	public int _maxItemsCount = 10;

	public List<T> _items = new List<T> ();

	public bool AddItem (T item)
	{
		if (_items.Count < _maxItemsCount) {
			_items.Add (item);
			return true;
		} 
		return false;
	}

	public T GetItem ()
	{
		if (_items.Count > 0) {
			T item = _items [0];
			_items.RemoveAt (0);
			return item;
		} else {
			return null;
		}
	}
}

